name: doorcab

description: "A Ride Healing Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# ---------- Packages ---------

dependencies:
  flutter:
    sdk: flutter

  # icons packages
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1

  # state management packages
  get: ^4.7.2


  # firebase packages

  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.1
  permission_handler: ^12.0.1

  # pusher + notification packages
  pusher_beams: ^1.1.2
  flutter_local_notifications: ^19.4.1
  pusher_channels_flutter: ^2.4.0

  # Url specific packages
  url_launcher: ^6.3.2

  # Utility packages
  intl: ^0.20.2
  http: ^1.4.0
  get_storage: ^2.1.1
  logger: ^2.6.1
  pinput: ^5.0.1
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  intl_phone_field: ^3.2.0
  slide_to_act: ^2.0.2


  # google maps packages
  google_maps_flutter: ^2.12.3
  geolocator: ^12.0.0
  geocoding: ^4.0.0
  location: ^8.0.1
  workmanager: ^0.9.0+3

  # Google Places Autocomplete
  google_places_flutter: ^2.1.1

# ----------- Packages End ----------

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"



  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

dependency_overrides:
  uuid: ^4.5.1
  geolocator: ^12.0.0
  pusher_beams_android:
    path: plugins/pusher_beams_android

flutter:
  uses-material-design: true

  # ---------- Local Assets -----------
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

  # ---------- Local Fonts ------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


    - family: Koulen
      fonts:
        - asset: assets/fonts/Koulen-Regular.ttf
          weight: 400