// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ecBV6yaSP-1iyJ5kpnFbFOaMvIyE2hs',
    appId: '1:147024698002:web:72e663a930eb6ef045a44b',
    messagingSenderId: '147024698002',
    projectId: 'doorcabs-f7a3e',
    authDomain: 'doorcabs-f7a3e.firebaseapp.com',
    storageBucket: 'doorcabs-f7a3e.firebasestorage.app',
    measurementId: 'G-MWV2Q450NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASYeq21zfVvYTgcaeaxqg0pTqx2oqEwns',
    appId: '1:147024698002:android:2cf350e162de71c945a44b',
    messagingSenderId: '147024698002',
    projectId: 'doorcabs-f7a3e',
    storageBucket: 'doorcabs-f7a3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSM07TyIXQ4Xo_aDPpQImkn9iyX0eAMGE',
    appId: '1:147024698002:ios:86515de4f7f6541445a44b',
    messagingSenderId: '147024698002',
    projectId: 'doorcabs-f7a3e',
    storageBucket: 'doorcabs-f7a3e.firebasestorage.app',
    iosBundleId: 'com.tricasol.doorcabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSM07TyIXQ4Xo_aDPpQImkn9iyX0eAMGE',
    appId: '1:147024698002:ios:5965e6b75e38690f45a44b',
    messagingSenderId: '147024698002',
    projectId: 'doorcabs-f7a3e',
    storageBucket: 'doorcabs-f7a3e.firebasestorage.app',
    iosBundleId: 'com.example.doorcab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ecBV6yaSP-1iyJ5kpnFbFOaMvIyE2hs',
    appId: '1:147024698002:web:306426b4c69f70a245a44b',
    messagingSenderId: '147024698002',
    projectId: 'doorcabs-f7a3e',
    authDomain: 'doorcabs-f7a3e.firebaseapp.com',
    storageBucket: 'doorcabs-f7a3e.firebasestorage.app',
    measurementId: 'G-3JQ9VJBJ5E',
  );
}
