import 'package:doorcab/splash/views/splash_screen.dart';
import 'package:doorcab/utils/http/http_client.dart';
import 'package:doorcab/utils/local_storage/storage_utility.dart';
import 'package:doorcab/utils/routes/app_pages.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';

// Import your Firebase, Pusher, Beams init code
// e.g., pusher setup, beams instance, etc.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize local storage before anything else
  await FLocalStorage.init();

  // ✅ Firebase initialization
  await Firebase.initializeApp();

  FHttpHelper.setBaseUrl("http://dc.tricasol.pk");
  // FHttpHelper.setBaseUrl("http://192.168.100.109:4000");

  // ✅ Pusher init
  // await PusherService.init();

  // ✅ Beams init
  // await BeamsService.init();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'DoorCabs',
      initialRoute: '/',
      getPages: AppPages.pages,
      home: const SplashScreen(), // Start with splash
    );
  }
}





// import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'package:permission_handler/permission_handler.dart';
// import 'package:pusher_beams/pusher_beams.dart';
// import 'firebase_options.dart'; // generated by flutterfire configure
//
// // Navigator key so we can show dialogs from anywhere
// final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
//
// // Top-level background handler for FCM (must be a top-level function)
// @pragma('vm:entry-point')
// Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   debugPrint(
//       '📩 [background] FCM message: ${message.messageId} title=${message.notification?.title} data=${message.data}');
// }
//
// Future<void> main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
//   runApp(const MyApp());
// }
//
// class MyApp extends StatelessWidget {
//   const MyApp({super.key});
//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       navigatorKey: navigatorKey,
//       debugShowCheckedModeBanner: false,
//       home: const HomeScreen(),
//     );
//   }
// }
//
// class HomeScreen extends StatefulWidget {
//   const HomeScreen({super.key});
//   @override
//   State<HomeScreen> createState() => _HomeScreenState();
// }
//
// class _HomeScreenState extends State<HomeScreen> {
//   final String beamsInstanceId = '1aeaf0d9-e6ba-4132-bee8-b152fe62ad54';
//   final String interest = 'passenger';
//
//   @override
//   void initState() {
//     super.initState();
//     initPushAndBeams();
//   }
//
//   Future<void> initPushAndBeams() async {
//     try {
//       // Request notification permission
//       final status = await Permission.notification.request();
//       if (!status.isGranted && !status.isLimited) {
//         debugPrint('❌ Notification permission denied');
//         return;
//       }
//       debugPrint('✅ Notification permission granted');
//
//       // Start Pusher Beams
//       await PusherBeams.instance.start(beamsInstanceId);
//       debugPrint('✅ Pusher Beams started with instance id: $beamsInstanceId');
//
//       // Listen for interest changes
//       PusherBeams.instance.onInterestChanges((interests) {
//         debugPrint('📌 Device interests updated: $interests');
//       });
//
//       // Get existing interests
//       final existing = await PusherBeams.instance.getDeviceInterests();
//       debugPrint('📌 Existing interests (from SDK): $existing');
//
//       if (!existing.contains(interest)) {
//         await PusherBeams.instance.addDeviceInterest(interest);
//         debugPrint("✅ addDeviceInterest('$interest') called");
//       } else {
//         debugPrint("ℹ️ Already subscribed to '$interest'");
//       }
//
//       // Confirm current interests
//       final after = await PusherBeams.instance.getDeviceInterests();
//       debugPrint('📋 Confirmed current interests: $after');
//
//       // Get FCM token
//       final fcmToken = await FirebaseMessaging.instance.getToken();
//       debugPrint('🔑 FCM token: $fcmToken');
//
//       // Foreground FCM listener
//       FirebaseMessaging.onMessage.listen((RemoteMessage msg) {
//         debugPrint(
//             '📩 FCM onMessage (foreground): ${msg.notification?.title} ${msg.notification?.body} data=${msg.data}');
//         final title = msg.notification?.title ??
//             msg.data['title']?.toString() ??
//             'No title';
//         final body =
//             msg.notification?.body ?? msg.data['body']?.toString() ?? 'No body';
//         _showNotificationDialog(title, body);
//       });
//
//       // Opened from notification
//       FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage msg) {
//         debugPrint('➡️ onMessageOpenedApp: ${msg.notification?.title}');
//       });
//
//       // Pusher Beams foreground listener
//       PusherBeams.instance
//           .onMessageReceivedInTheForeground((notification) {
//         debugPrint('📩 Pusher Beams foreground notification: $notification');
//
//         // Safely extract APNS (iOS) payload
//         final aps = (notification['aps'] is Map)
//             ? notification['aps'] as Map
//             : null;
//         final alert =
//         (aps != null && aps['alert'] is Map) ? aps['alert'] as Map : null;
//
//         final title = notification['title']?.toString() ??
//             alert?['title']?.toString() ??
//             'No title';
//         final body = notification['body']?.toString() ??
//             alert?['body']?.toString() ??
//             '';
//
//         _showNotificationDialog(title, body);
//       });
//
//       debugPrint('✅ Push / Beams initialization complete.');
//     } catch (e, st) {
//       debugPrint('❌ initPushAndBeams error: $e\n$st');
//     }
//   }
//
//   void _showNotificationDialog(String title, String body) {
//     final ctx = navigatorKey.currentState?.overlay?.context;
//     if (ctx == null) {
//       debugPrint('⚠️ navigator context not ready - skipping dialog');
//       return;
//     }
//
//     showDialog(
//       context: ctx,
//       builder: (_) => AlertDialog(
//         title: Text(title),
//         content: Text(body),
//         actions: [
//           TextButton(
//             onPressed: () => Navigator.of(ctx).pop(),
//             child: const Text('OK'),
//           ),
//         ],
//       ),
//     );
//   }
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: const Text('Pusher Beams + FCM Test')),
//       body: Center(
//         child: Column(
//           mainAxisSize: MainAxisSize.min,
//           children: [
//             const Text('Ready — listening for notifications...'),
//             const SizedBox(height: 16),
//             ElevatedButton(
//               onPressed: () async {
//                 final interests =
//                 await PusherBeams.instance.getDeviceInterests();
//                 final token = await FirebaseMessaging.instance.getToken();
//                 debugPrint('📌 Current interests: $interests');
//                 debugPrint('🔑 FCM token (again): $token');
//                 ScaffoldMessenger.of(context).showSnackBar(
//                   SnackBar(content: Text('Interests: $interests')),
//                 );
//               },
//               child: const Text('Check subscriptions & token'),
//             ),
//           ],
//         ),
//       ),
//     );
//   }
// }
